pipeline {
    agent any {
    stages {
        stage('Build') {
            steps {
                sh 'echo "This is the first step"'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "This is the second step"'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
